import type {
  NavLink,
  CaseStudy,
  Service,
  Stat,
  Testimonial,
  Article,
  TrustItem,
} from "@/types";

export const navLinks: NavLink[] = [
  { label: "Portfolio", href: "/work" },
  { label: "Services", href: "/services" },
  { label: "About", href: "/about" },
  { label: "Blog", href: "/blogs" },
  {
    label: "SEO Tools",
    href: "/seo-tools",
    children: [
      { label: "Analyze URL", href: "/seo-tools", description: "On-page SEO checks, keywords & backlinks" },
      { label: "Site Audit", href: "/seo-tools/site-audit", description: "Crawl every page — no limits, 50+ checks" },
    ],
  },
  { label: "Contact", href: "/contact" },
];

export const trustItems: TrustItem[] = [
  { label: "Next.js" },
  { label: "React" },
  { label: "TypeScript" },
  { label: "WordPress" },
  { label: "Shopify" },
  { label: "Tailwind CSS" },
  { label: "SEO / AEO / GEO" },
  { label: "n8n Automation" },
];

export const caseStudies: CaseStudy[] = [
  /* ── Next.js Website & Web App Projects ──────────────────────── */
  {
    id: "tacklers-consulting",
    client: "Tacklers Consulting",
    title: "Full-stack consulting platform built with Next.js, Prisma, and Supabase",
    problem: "No web presence. Needed a professional website + internal web app for client management.",
    result: "Full-stack Next.js platform shipped with auth, dashboard, and SEO",
    tags: ["Next.js", "React", "TypeScript", "Prisma", "Supabase", "Tailwind CSS"],
    thumbnail: "/1.png",
    metrics: [
      { label: "Tech Stack", value: "Next.js", icon: "code", description: "Full-stack Next.js application with server components, API routes, and Prisma ORM." },
      { label: "Features", value: "12+", positive: true, icon: "layout-dashboard", description: "Auth, client dashboard, contact forms, blog CMS, analytics, and SEO optimization." },
      { label: "Performance", value: "95+", positive: true, icon: "gauge", description: "Lighthouse score across performance, accessibility, and SEO." },
    ],
    href: "/work/tacklers-consulting",
    subtitle: "A complete digital platform for a consulting business.",
    duration: "Full-Stack Build",
    accentColor: "violet",
    url: "https://www.tacklersconsulting.com/",
    challengeHeading: "A consulting firm with no digital infrastructure.",
    challengeDescription: [
      "Tacklers Consulting needed more than a brochure website — they needed a full digital platform to manage clients, showcase services, and generate leads through organic search.",
      "The project required authentication, a client dashboard, content management, and best-in-class SEO — all built from scratch on a modern stack.",
    ],
    challengeItems: [
      { icon: "globe", title: "No Web Presence", description: "Zero online footprint — no website, no search visibility, and no way for clients to engage digitally." },
      { icon: "layout-dashboard", title: "Complex Requirements", description: "Auth system, client portal, blog CMS, analytics dashboard — far beyond a template site." },
      { icon: "search", title: "SEO Critical", description: "Organic search was the primary client acquisition channel — SEO had to be baked in from day one." },
    ],
    strategyHeading: "Full-stack development with SEO-first architecture.",
    strategyItems: [
      { icon: "code", title: "Next.js App Router", description: "Built on Next.js with server components, streaming, and optimized rendering for Core Web Vitals.", color: "violet" },
      { icon: "database", title: "Prisma + Supabase", description: "PostgreSQL database via Supabase with Prisma ORM for type-safe data access, migrations, and seeding.", color: "cyan" },
      { icon: "search", title: "SEO Architecture", description: "Keyword-mapped pages, structured data (JSON-LD), dynamic sitemap, meta tags, and Open Graph — built into every route.", color: "violet" },
    ],
    quote: { text: "Shree built exactly what we needed — a website that looks professional and a backend that actually works. Everything from auth to SEO was handled.", author: "Founder" },
  },
  {
    id: "focus-your-finance",
    client: "Focus Your Finance",
    title: "Finance platform with Next.js — client portal, tools, and SEO-optimized content",
    problem: "Needed a modern finance platform with interactive tools and content strategy.",
    result: "Full-stack Next.js finance platform with SEO-driven content system",
    tags: ["Next.js", "React", "TypeScript", "Prisma", "Tailwind CSS", "SEO"],
    thumbnail: "/2.png",
    metrics: [
      { label: "Platform", value: "Next.js", icon: "code", description: "Server-rendered finance platform with interactive calculators and content hub." },
      { label: "Page Speed", value: "97", positive: true, icon: "gauge", description: "Near-perfect Lighthouse performance score through optimized rendering and caching." },
      { label: "SEO Pages", value: "30+", positive: true, icon: "file-text", description: "Keyword-targeted pages covering core finance topics for organic growth." },
    ],
    href: "/work/focus-your-finance",
    subtitle: "Finance meets modern web — fast, optimized, and built to rank.",
    duration: "Full-Stack Build",
    accentColor: "cyan",
    url: "https://focusyourfinance.com/",
    challengeHeading: "A finance brand that needed more than a blog.",
    challengeDescription: [
      "Focus Your Finance needed a platform that could educate users, provide interactive financial tools, and rank for competitive finance keywords — all while maintaining a premium, trustworthy design.",
      "The existing approach of scattered content and no web app infrastructure was limiting growth and failing to convert visitors into engaged users.",
    ],
    challengeItems: [
      { icon: "trending-down", title: "No Organic Presence", description: "Finance is one of the most competitive SEO verticals — they had zero search visibility." },
      { icon: "layout-dashboard", title: "Interactive Tools Needed", description: "Users expected calculators, compare tools, and personalized content — not static pages." },
      { icon: "shield", title: "Trust & Credibility", description: "Finance content requires E-E-A-T signals, professional design, and fast, secure infrastructure." },
    ],
    strategyHeading: "A platform built for authority and engagement.",
    strategyItems: [
      { icon: "code", title: "Next.js Full Stack", description: "Server-rendered pages for SEO, client components for interactivity, and API routes for tool calculations.", color: "cyan" },
      { icon: "file-text", title: "Content Architecture", description: "30+ SEO-optimized pages with keyword mapping, internal linking, and structured data for rich snippets.", color: "violet" },
      { icon: "shield", title: "Trust Signals", description: "Professional UI, fast load times, HTTPS, schema markup, and E-E-A-T compliant content structure.", color: "cyan" },
    ],
    quote: { text: "The site feels like a fintech product, not a blog. Users stay longer, engage with tools, and we're finally ranking for terms we care about.", author: "Founder" },
  },
  {
    id: "get-focus-health",
    client: "Get Focus Health",
    title: "Health & wellness web app — Next.js with patient tools, content hub, and SEO",
    problem: "Needed a modern health platform that educates, engages, and ranks on search engines.",
    result: "Full-stack health platform with 95+ Lighthouse scores and growing organic traffic",
    tags: ["Next.js", "React", "TypeScript", "Tailwind CSS", "SEO", "Healthcare"],
    thumbnail: "/3.png",
    metrics: [
      { label: "Stack", value: "Next.js", icon: "code", description: "Full-stack Next.js health platform with server components and API routes." },
      { label: "Lighthouse", value: "95+", positive: true, icon: "gauge", description: "Top scores across performance, SEO, accessibility, and best practices." },
      { label: "Content Pages", value: "25+", positive: true, icon: "file-text", description: "Health topics mapped to search intent for organic patient acquisition." },
    ],
    href: "/work/get-focus-health",
    subtitle: "Healthcare content meets modern web performance.",
    duration: "Full-Stack Build",
    accentColor: "violet",
    url: "https://getfocushealth.com/",
    challengeHeading: "A health brand competing against established medical sites.",
    challengeDescription: [
      "Get Focus Health needed to break into the healthcare search space — dominated by WebMD, Healthline, and hospital networks — with a modern, fast, and trustworthy web platform.",
      "Beyond content, they needed interactive health tools, a resource hub, and a design that conveyed medical credibility while remaining approachable.",
    ],
    challengeItems: [
      { icon: "shield", title: "YMYL Content", description: "Health content falls under Google's 'Your Money or Your Life' category — requiring highest E-E-A-T standards." },
      { icon: "search", title: "Competitive SERP", description: "Healthcare search results are dominated by billion-dollar brands with decades of domain authority." },
      { icon: "users", title: "Patient Experience", description: "Users needed health information presented clearly, with fast load times and mobile-first design." },
    ],
    strategyHeading: "Medical-grade web architecture.",
    strategyItems: [
      { icon: "code", title: "Next.js Platform", description: "Server-side rendering for SEO, optimized images, and streaming for the fastest possible page loads.", color: "violet" },
      { icon: "file-text", title: "YMYL Content Strategy", description: "Expert-reviewed health content with proper schema markup, author attribution, and medical disclaimers.", color: "cyan" },
      { icon: "search", title: "Technical SEO", description: "Dynamic sitemaps, canonical tags, structured data, and Core Web Vitals optimization from day one.", color: "violet" },
    ],
    quote: { text: "We're competing with sites 100x our size — and winning specific keywords because our site is faster, cleaner, and better structured.", author: "Founder" },
  },
  {
    id: "focus-data",
    client: "Focus Data",
    title: "Data analytics platform built with Next.js — dashboards, API integrations, and real-time reporting",
    problem: "Needed a custom data platform to visualize analytics and integrate multiple data sources.",
    result: "Full-stack data platform with real-time dashboards and API-driven architecture",
    tags: ["Next.js", "React", "TypeScript", "Prisma", "API Integrations", "Dashboards"],
    thumbnail: "/1.png",
    metrics: [
      { label: "Platform", value: "Next.js", icon: "code", description: "Custom data analytics platform with server components and real-time updates." },
      { label: "Integrations", value: "5+", positive: true, icon: "workflow", description: "Connected to multiple data sources via REST APIs and webhooks." },
      { label: "Dashboards", value: "Real-time", positive: true, icon: "layout-dashboard", description: "Live updating dashboards with chart visualizations and data exports." },
    ],
    href: "/work/focus-data",
    subtitle: "Turn raw data into actionable dashboards.",
    duration: "Web App Build",
    accentColor: "cyan",
    url: "http://focusdata.io/",
    challengeHeading: "Scattered data across dozens of tools with no single source of truth.",
    challengeDescription: [
      "Focus Data needed a centralized platform to aggregate data from multiple sources, visualize it in real-time dashboards, and provide actionable insights — all in one place.",
      "Off-the-shelf tools were too rigid and expensive. They needed a custom solution that matched their exact workflows and could evolve with their needs.",
    ],
    challengeItems: [
      { icon: "database", title: "Data Silos", description: "Critical data trapped in 5+ different tools with no unified view." },
      { icon: "bar-chart-3", title: "Manual Reporting", description: "Hours spent each week pulling data from multiple dashboards and compiling into spreadsheets." },
      { icon: "workflow", title: "No Automation", description: "Data collection, transformation, and reporting was entirely manual." },
    ],
    strategyHeading: "A custom data platform built for speed.",
    strategyItems: [
      { icon: "code", title: "Next.js Web App", description: "Full-stack application with server components for data fetching and client components for interactive charts.", color: "cyan" },
      { icon: "workflow", title: "API Architecture", description: "RESTful API layer connecting to 5+ data sources with automated syncing and webhook-driven updates.", color: "violet" },
      { icon: "layout-dashboard", title: "Real-Time Dashboards", description: "Interactive chart components with filtering, date ranges, and CSV export capabilities.", color: "cyan" },
    ],
    quote: { text: "We replaced 3 paid dashboard tools with one custom platform that does exactly what we need — and it's faster than all of them.", author: "CEO" },
  },
  {
    id: "naperville-hwc",
    client: "Naperville Health & Wellness Clinic",
    title: "Healthcare clinic web app — patient portal, appointment booking, and local SEO",
    problem: "Needed a HIPAA-aware clinic website with patient tools and local search visibility.",
    result: "Next.js clinic platform with booking system, patient resources, and local SEO",
    tags: ["Next.js", "React", "TypeScript", "Healthcare", "Local SEO", "Tailwind CSS"],
    thumbnail: "/2.png",
    metrics: [
      { label: "Stack", value: "Next.js", icon: "code", description: "Full-stack clinic platform with appointment booking and patient resource portal." },
      { label: "Local SEO", value: "Live", positive: true, icon: "map-pin", description: "Google Business Profile optimized, local citations built, schema markup deployed." },
      { label: "Performance", value: "96", positive: true, icon: "gauge", description: "Lighthouse performance score — faster than 95% of healthcare websites." },
    ],
    href: "/work/naperville-hwc",
    subtitle: "A clinic website that books patients, not just displays information.",
    duration: "Full-Stack Build",
    accentColor: "amber",
    url: "https://napervillehwclinic.com/",
    challengeHeading: "A new clinic invisible to local patients searching online.",
    challengeDescription: [
      "Naperville Health & Wellness Clinic needed more than a brochure site — they needed a platform with appointment booking, patient resources, and strong local search presence.",
      "In a competitive Naperville healthcare market, they required a website that ranked for local health searches and converted visitors into booked appointments.",
    ],
    challengeItems: [
      { icon: "globe", title: "No Digital Presence", description: "Brand-new clinic with no website, no domain history, and no search visibility." },
      { icon: "calendar", title: "Booking Friction", description: "Patients had no way to book online — all scheduling was phone-only during business hours." },
      { icon: "map-pin", title: "Local Competition", description: "Established clinics dominated local search results with years of reviews and backlink history." },
    ],
    strategyHeading: "A patient-first digital experience.",
    strategyItems: [
      { icon: "code", title: "Next.js Clinic Platform", description: "Server-rendered pages for maximum SEO, with client-side booking widget and patient resource portal.", color: "amber" },
      { icon: "map-pin", title: "Local SEO Foundation", description: "Google Business Profile optimization, local schema markup, NAP citations, and geo-targeted service pages.", color: "violet" },
      { icon: "calendar", title: "Online Booking", description: "Integrated appointment scheduling system allowing 24/7 booking with automated confirmations.", color: "amber" },
    ],
    quote: { text: "Within weeks of launch, we had patients telling us they found us on Google. The booking system alone was worth it — we get appointments at midnight now.", author: "Clinic Director" },
  },

  /* ── WordPress Projects ──────────────────────────────────────── */
  {
    id: "erof-white-rock",
    client: "EROF White Rock",
    title: "Healthcare clinic WordPress site — professional design, SEO, and patient experience",
    problem: "Needed a professional clinic website quickly with strong local search visibility.",
    result: "WordPress clinic site live and ranking for local healthcare searches",
    tags: ["WordPress", "Healthcare", "SEO", "Responsive Design", "Local SEO"],
    thumbnail: "/3.png",
    metrics: [
      { label: "Platform", value: "WordPress", icon: "code", description: "Custom WordPress build with optimized theme, SEO, and mobile-responsive design." },
      { label: "Local SEO", value: "Active", positive: true, icon: "map-pin", description: "Google Business Profile integration, local citations, and geo-targeted content." },
      { label: "Mobile", value: "100%", positive: true, icon: "smartphone", description: "Fully responsive design optimized for mobile-first patient experience." },
    ],
    href: "/work/erof-white-rock",
    subtitle: "A WordPress clinic site built for trust and local rankings.",
    duration: "WordPress Build",
    accentColor: "violet",
    url: "https://erofwhiterock.com/",
    challengeHeading: "A healthcare practice needing immediate web presence.",
    challengeDescription: [
      "EROF White Rock needed a professional clinic website that communicated medical credibility, provided clear service information, and ranked in local search results.",
      "Speed to launch was essential — the practice was operational and losing potential patients every day without an online presence.",
    ],
    challengeItems: [
      { icon: "globe", title: "No Website", description: "Operating without any web presence in a market where patients Google before booking." },
      { icon: "shield", title: "Medical Credibility", description: "Healthcare sites require professional design that signals trust and competence." },
      { icon: "clock", title: "Fast Turnaround", description: "The practice needed to be online quickly — every week without a site meant lost patients." },
    ],
    strategyHeading: "WordPress built for healthcare.",
    strategyItems: [
      { icon: "code", title: "Custom WordPress Theme", description: "Clean, professional design tailored for healthcare with optimized page speed and mobile responsiveness.", color: "violet" },
      { icon: "search", title: "On-Page SEO", description: "Keyword-optimized service pages, meta tags, schema markup, and XML sitemap for search visibility.", color: "cyan" },
      { icon: "map-pin", title: "Local Optimization", description: "Google Business Profile setup, local citation building, and NAP consistency for map pack visibility.", color: "violet" },
    ],
    quote: { text: "The site looks like we spent 10x what we did. Patients comment on how professional it looks — and we're showing up in Google Maps now.", author: "Practice Manager" },
  },
  {
    id: "erof-lufkin",
    client: "EROF Lufkin",
    title: "WordPress healthcare site for Lufkin clinic — local SEO and patient-first design",
    problem: "New clinic location needed a branded website matching the EROF network standards.",
    result: "Branded WordPress site launched with local SEO foundation",
    tags: ["WordPress", "Healthcare", "Local SEO", "Responsive Design"],
    thumbnail: "/1.png",
    metrics: [
      { label: "Platform", value: "WordPress", icon: "code", description: "WordPress healthcare site with custom design and professional medical layout." },
      { label: "Brand", value: "Consistent", positive: true, icon: "paintbrush", description: "Design consistent with the EROF network brand across multiple locations." },
      { label: "Local SEO", value: "Active", positive: true, icon: "map-pin", description: "Geo-targeted content and Google Business Profile optimized for Lufkin area." },
    ],
    href: "/work/erof-lufkin",
    subtitle: "Extending the EROF brand to a new market.",
    duration: "WordPress Build",
    accentColor: "cyan",
    url: "http://eroflufkin.com/",
    challengeHeading: "A new location needing branded web presence fast.",
    challengeDescription: [
      "EROF Lufkin was a new location in the EROF healthcare network. They needed a website that matched the brand standard of existing locations while targeting the Lufkin-specific patient market.",
      "The site needed to look and feel like part of the EROF family while incorporating location-specific content for local SEO.",
    ],
    challengeItems: [
      { icon: "map-pin", title: "New Market", description: "Lufkin area patients had no awareness of EROF — the website needed to build local trust from zero." },
      { icon: "paintbrush", title: "Brand Consistency", description: "The site had to match the EROF brand while being uniquely optimized for the Lufkin market." },
      { icon: "search", title: "Local Competition", description: "Established Lufkin clinics already dominated local search results." },
    ],
    strategyHeading: "Branded WordPress for a new market.",
    strategyItems: [
      { icon: "code", title: "WordPress Build", description: "Custom WordPress site matching EROF brand guidelines with location-specific content and imagery.", color: "cyan" },
      { icon: "map-pin", title: "Lufkin Local SEO", description: "Geo-targeted service pages, Lufkin-specific keywords, and Google Business Profile optimization.", color: "violet" },
      { icon: "users", title: "Patient Experience", description: "Clear service descriptions, provider bios, contact information, and mobile-optimized design.", color: "cyan" },
    ],
    quote: { text: "The site brought our Lufkin brand to life. Patients tell us they found us searching online — that wasn't happening before.", author: "Regional Director" },
  },
  {
    id: "erof-irving",
    client: "EROF Irving",
    title: "WordPress healthcare site for Irving location — SEO, patient tools, and brand alignment",
    problem: "Another EROF network location needed a branded clinic website with local search optimization.",
    result: "Professional WordPress clinic site with local search visibility",
    tags: ["WordPress", "Healthcare", "Local SEO", "Responsive Design"],
    thumbnail: "/2.png",
    metrics: [
      { label: "Platform", value: "WordPress", icon: "code", description: "WordPress healthcare site with custom theme matching EROF network branding." },
      { label: "Speed", value: "Fast", positive: true, icon: "gauge", description: "Optimized WordPress build with caching, image compression, and clean code." },
      { label: "Local Rank", value: "Active", positive: true, icon: "map-pin", description: "Ranking for Irving-specific healthcare searches in the local pack." },
    ],
    href: "/work/erof-irving",
    subtitle: "Professional healthcare presence for the Irving market.",
    duration: "WordPress Build",
    accentColor: "violet",
    url: "https://erofirving.com/",
    challengeHeading: "Establishing EROF's presence in the Irving healthcare market.",
    challengeDescription: [
      "EROF Irving needed a website that positioned the clinic as a trusted healthcare provider in the Irving area — competing with established local practices.",
      "The site had to maintain brand consistency with the broader EROF network while targeting Irving-specific patients and search terms.",
    ],
    challengeItems: [
      { icon: "map-pin", title: "Irving Market", description: "The Irving healthcare market was competitive with established clinics dominating local search." },
      { icon: "globe", title: "Online Visibility", description: "Without a website, the Irving location was invisible to patients searching online." },
      { icon: "shield", title: "Trust Factor", description: "New clinic locations need to immediately convey credibility and professionalism." },
    ],
    strategyHeading: "WordPress tailored for the Irving market.",
    strategyItems: [
      { icon: "code", title: "Custom Theme", description: "WordPress build with EROF branding, optimized for performance and mobile responsiveness.", color: "violet" },
      { icon: "search", title: "Irving SEO", description: "Location-specific keyword targeting, Google Business Profile optimization, and local citation building.", color: "cyan" },
      { icon: "shield", title: "Credibility Design", description: "Professional layout with provider credentials, certifications, and patient-friendly service descriptions.", color: "violet" },
    ],
    quote: { text: "We saw patients start mentioning they found us online within the first month. The website paid for itself quickly.", author: "Clinic Manager" },
  },
  {
    id: "irving-wellness",
    client: "Irving Wellness Clinic",
    title: "Wellness clinic WordPress site — holistic health design with SEO and booking integration",
    problem: "A wellness clinic needed a modern website to attract health-conscious patients in Irving.",
    result: "WordPress wellness site with booking integration and growing organic presence",
    tags: ["WordPress", "Healthcare", "Wellness", "SEO", "Responsive Design"],
    thumbnail: "/3.png",
    metrics: [
      { label: "Platform", value: "WordPress", icon: "code", description: "Custom WordPress site designed for the wellness and holistic health space." },
      { label: "Design", value: "Premium", positive: true, icon: "paintbrush", description: "Calming, professional design language tailored for wellness patients." },
      { label: "Booking", value: "Online", positive: true, icon: "calendar", description: "Integrated booking system for seamless patient scheduling." },
    ],
    href: "/work/irving-wellness",
    subtitle: "Where wellness meets the web — designed for trust and conversion.",
    duration: "WordPress Build",
    accentColor: "amber",
    url: "https://irvingwellnessclinic.com/",
    challengeHeading: "A wellness practice needing differentiated online presence.",
    challengeDescription: [
      "Irving Wellness Clinic offered holistic and wellness services but had no dedicated website — relying entirely on referrals and social media for new patients.",
      "The wellness space requires a specific design language — calming, natural, and trustworthy — that generic healthcare templates fail to deliver.",
    ],
    challengeItems: [
      { icon: "heart", title: "Niche Market", description: "Wellness patients have different expectations — the site needed to feel holistic, not clinical." },
      { icon: "globe", title: "No Web Presence", description: "Operating without a website in a market increasingly researched online before booking." },
      { icon: "calendar", title: "No Online Booking", description: "All appointments were phone-only, limiting accessibility and after-hours bookings." },
    ],
    strategyHeading: "Wellness-first WordPress design.",
    strategyItems: [
      { icon: "paintbrush", title: "Wellness Design", description: "Custom WordPress theme with calming aesthetics, natural color palette, and wellness-focused imagery.", color: "amber" },
      { icon: "calendar", title: "Booking Integration", description: "Online appointment scheduling allowing 24/7 booking with automated email confirmations.", color: "violet" },
      { icon: "search", title: "Wellness SEO", description: "Content optimized for wellness and holistic health searches in the Irving, TX area.", color: "amber" },
    ],
    quote: { text: "Patients say our website feels exactly like our clinic — calm, professional, and welcoming. That's hard to get right.", author: "Practice Owner" },
  },

  /* ── Shopify Project ─────────────────────────────────────────── */
  {
    id: "olivia-tanghulu",
    client: "Olivia's Tanghulu",
    title: "Shopify e-commerce store — custom theme, product showcase, and SEO-optimized store",
    problem: "Needed an e-commerce presence to sell tanghulu treats online with eye-catching product pages.",
    result: "Shopify store live with custom design, product pages, and SEO foundation",
    tags: ["Shopify", "E-Commerce", "Custom Theme", "SEO", "Product Design"],
    thumbnail: "/1.png",
    metrics: [
      { label: "Platform", value: "Shopify", icon: "shopping-cart", description: "Custom Shopify store with optimized product pages and checkout flow." },
      { label: "Products", value: "Live", positive: true, icon: "package", description: "Full product catalog with high-quality imagery, descriptions, and variant options." },
      { label: "SEO", value: "Built-in", positive: true, icon: "search", description: "Store optimized for product and brand search with meta tags, alt text, and structured data." },
    ],
    href: "/work/olivia-tanghulu",
    subtitle: "Sweet treats deserve a sweet storefront.",
    duration: "Shopify Build",
    accentColor: "amber",
    url: "https://oliviastanghulu.com/",
    challengeHeading: "A food brand ready to sell online — but no storefront.",
    challengeDescription: [
      "Olivia's Tanghulu had a growing local following for their sugar-coated fruit treats but no way to sell online. They needed an e-commerce store that matched the visual appeal of their product.",
      "The store needed to be easy to manage, visually stunning, and optimized for both local and online discovery.",
    ],
    challengeItems: [
      { icon: "shopping-cart", title: "No Online Store", description: "Sales were happening in-person only — missing the entire online market." },
      { icon: "paintbrush", title: "Visual Product", description: "Tanghulu is a visually stunning product — the store design needed to match that appeal." },
      { icon: "smartphone", title: "Mobile Commerce", description: "Target customers primarily browse and buy on mobile — the store had to be mobile-first." },
    ],
    strategyHeading: "A Shopify store as appealing as the product.",
    strategyItems: [
      { icon: "code", title: "Custom Shopify Theme", description: "Designed a custom Shopify theme that showcases the vibrant, colorful nature of tanghulu products.", color: "amber" },
      { icon: "package", title: "Product Setup", description: "Professional product photography display, variant management, inventory tracking, and optimized checkout.", color: "violet" },
      { icon: "search", title: "E-Commerce SEO", description: "Product schema markup, meta descriptions, alt text, and collection page optimization for organic discovery.", color: "amber" },
    ],
    quote: { text: "People always said our tanghulu looked too good — now the website matches. Online orders started coming in the first week.", author: "Olivia, Founder" },
  },

  /* ── Existing SEO & Automation Case Studies ──────────────────── */
  {
    id: "seo-growth",
    client: "Healthcare SaaS",
    title: "Organic search rebuilt from near-zero to consistent top-10 rankings",
    problem: "No SEO foundation. Thin content. Zero domain presence.",
    result: "340% increase in organic sessions over 8 months",
    tags: ["SEO", "Content Strategy", "Technical SEO"],
    thumbnail: "/1.png",
    metrics: [
      { label: "Organic Growth", value: "+340%", positive: true, icon: "trending-up", description: "Sustainable traffic increase across core high-intent search terms that convert." },
      { label: "Keywords Ranked", value: "120+", positive: true, icon: "key-round", description: "Top-tier industry phrases securing permanent Page 1 visibility for the first time." },
      { label: "ROI Timeline", value: "8 mo.", icon: "timer", description: "From foundational technical audit to a market-leading authority." },
    ],
    href: "/work/seo-growth",
    subtitle: "A zero-to-top-10 ranking transformation.",
    duration: "8 Month Implementation",
    accentColor: "violet",
    challengeHeading: "The invisible wall blocking patient acquisition.",
    challengeDescription: [
      "Despite having a market-leading product, the brand was digitally non-existent. Their technical architecture functioned as a digital barrier, effectively blocking search engine crawlers from ever discovering their most critical clinical content.",
      "We identified a critical lack of SEO foundation: thin, superficial service pages that failed to speak the language of healthcare professionals, coupled with a complete absence of domain authority. They weren\u2019t just losing\u2014they weren\u2019t even in the race.",
    ],
    challengeItems: [
      { icon: "bug", title: "Crawlability Barriers", description: "JS-heavy rendering hiding 80% of clinical documentation from Google." },
      { icon: "layers", title: "Thin Semantic Depth", description: "Keywords lacked the medical specificity required for E-E-A-T compliance." },
      { icon: "unlink", title: "Zero Authority", description: "A non-existent backlink profile against legacy giants with 15+ years of tenure." },
    ],
    strategyHeading: "A precision surgical approach to SEO.",
    strategyItems: [
      { icon: "wrench", title: "Technical Cleanup", description: "Re-engineered the site architecture to ensure every high-value page was indexed within 48 hours of publication.", color: "violet" },
      { icon: "file-text", title: "Content Deployment", description: "Deployment of 50+ deep-dive clinical whitepapers addressing exact search intent of medical decision makers.", color: "cyan" },
      { icon: "network", title: "Authority Mapping", description: "Strategic backlink acquisition from Tier-1 medical publications and SaaS industry leaders.", color: "violet" },
    ],
    quote: { text: "The transformation was immediate. Within 12 weeks, our indexing coverage jumped from 18% to 99%.", author: "Head of Engineering" },
  },
  {
    id: "automation",
    client: "Local Services Group",
    title: "Automated reporting and lead pipeline saving 20+ hours per week",
    problem: "Manual reporting, missed leads, no process consistency.",
    result: "20+ hours saved weekly via n8n automation",
    tags: ["n8n", "CRM", "Automation", "Reporting"],
    thumbnail: "/3.png",
    metrics: [
      { label: "Hours Saved / Week", value: "20+", positive: true, icon: "clock", description: "Reclaimed from repetitive data entry, report generation, and tool syncing." },
      { label: "Lead Response Time", value: "-85%", positive: true, icon: "zap", description: "From 6+ hours to under 15 minutes through automated routing and alerts." },
      { label: "Pipelines Built", value: "7", icon: "workflow", description: "Interconnected n8n workflows handling every step from lead to close." },
    ],
    href: "/work/automation",
    subtitle: "From manual chaos to autonomous operations.",
    duration: "6 Week Build",
    accentColor: "amber",
    challengeHeading: "Drowning in manual processes nobody owns.",
    challengeDescription: [
      "The team was spending 20+ hours per week on repetitive tasks: copying data between tools, manually generating reports, and chasing leads that fell through the cracks.",
      "Without any automation infrastructure, every process depended on someone remembering to do it. Lead response times averaged 6+ hours, and weekly reports took an entire day to compile.",
    ],
    challengeItems: [
      { icon: "clock", title: "Manual Everything", description: "20+ hours/week spent on repetitive data entry, report generation, and tool syncing." },
      { icon: "alert-triangle", title: "Missed Leads", description: "Average response time of 6+ hours, with 15% of leads never receiving a response." },
      { icon: "file-spreadsheet", title: "Report Hell", description: "Weekly client reports took 8+ hours to compile from 5 different data sources." },
    ],
    strategyHeading: "An automation-first infrastructure overhaul.",
    strategyItems: [
      { icon: "workflow", title: "n8n Workflow Engine", description: "Built 7 interconnected workflows handling lead routing, data sync, and notification chains.", color: "amber" },
      { icon: "database", title: "CRM Integration", description: "Unified 5 data sources into a single CRM pipeline with automatic stage progression and alerts.", color: "violet" },
      { icon: "layout-dashboard", title: "Live Dashboards", description: "Real-time reporting dashboards replacing manual weekly report compilation entirely.", color: "amber" },
    ],
    quote: { text: "What used to take half a day now runs overnight without anyone touching it. Game-changing for a small team.", author: "Operations Manager" },
  },
  {
    id: "seo-website-launch",
    client: "New Clinic Launch",
    title: "From zero to 9.41K impressions in 60 days with a one-day website build",
    problem: "Brand-new clinic with no website, no domain authority, and zero online presence.",
    result: "9.41K impressions and 252 organic clicks within 2 months",
    tags: ["SEO", "Web Development", "Local SEO", "Google Search Console"],
    thumbnail: "/case-study-seo-search-console.png",
    metrics: [
      { label: "Impressions", value: "9.41K", positive: true, icon: "eye", description: "Appeared in front of 9,410 potential patients within the first 60 days of launch." },
      { label: "Organic Clicks", value: "252", positive: true, icon: "mouse-pointer-click", description: "252 real visitors from Google without a single dollar spent on ads." },
      { label: "Website Build Time", value: "1 Day", icon: "timer", description: "From concept to a fully SEO-optimized, mobile-ready, live website in a single day." },
    ],
    href: "/work/seo-website-launch",
    subtitle: "A one-day build that started ranking in weeks.",
    duration: "1 Day Build + 2 Month Results",
    accentColor: "cyan",
    challengeHeading: "A brand-new clinic with zero digital presence.",
    challengeDescription: [
      "This client had just launched a new clinic and had nothing online — no website, no Google Business Profile optimization, and no domain history. They were starting from absolute zero in one of the most competitive local markets: healthcare.",
      "Speed was critical. The clinic was already open and seeing walk-ins, but without any web presence, they were invisible to the thousands of patients searching for care in their area every day.",
    ],
    challengeItems: [
      { icon: "globe", title: "No Website or Domain", description: "Zero online footprint — no website, no indexed pages, and no domain authority to build from." },
      { icon: "map-pin", title: "Competitive Local Market", description: "Healthcare search in their area was dominated by established clinics with years of SEO history." },
      { icon: "clock", title: "Time-Sensitive Launch", description: "The clinic was already operational. Every day without a website meant lost patients to competitors." },
    ],
    strategyHeading: "A rapid, SEO-first website launch.",
    strategyItems: [
      { icon: "code", title: "One-Day Website Build", description: "Designed and deployed a fully responsive, mobile-optimized website in a single day with proper site architecture, meta tags, schema markup, and fast Core Web Vitals.", color: "cyan" },
      { icon: "search", title: "SEO From Day One", description: "Every page built with keyword-mapped content targeting high-intent local searches. Sitemap submitted to Google Search Console on launch day.", color: "violet" },
      { icon: "map-pin", title: "Local SEO Setup", description: "Google Business Profile optimization, local citation building, and NAP consistency across directories to boost local pack visibility.", color: "cyan" },
    ],
    quote: { text: "We went from zero to showing up on Google in less than two weeks. By the end of month two, we had real patients finding us through search.", author: "Clinic Founder" },
    proofImage: { src: "/case-study-seo-search-console.png", alt: "Google Search Console showing 9.41K impressions and 252 clicks within 2 months of launch", caption: "Google Search Console — 60-day performance after launch" },
    takeaway: "You don't need months to build a website that ranks. With the right SEO foundation from day one, even a brand-new domain can generate meaningful organic traffic within weeks.",
  },
  {
    id: "ai-call-centre",
    client: "Service-Based Business",
    title: "AI call centre agent turns missed leads into 10–12 new clients per month",
    problem: "Inconsistent manual follow-up causing leads to go cold and revenue to leak.",
    result: "10–12 new leads per month through AI-powered follow-up",
    tags: ["AI Automation", "Lead Follow-Up", "Conversational AI", "CRM"],
    thumbnail: "/3.png",
    metrics: [
      { label: "New Leads / Month", value: "10–12", positive: true, icon: "trending-up", description: "Consistent monthly lead flow generated entirely by the AI call agent." },
      { label: "Follow-Up Speed", value: "<1 min", positive: true, icon: "zap", description: "Every lead gets an immediate AI-powered response with zero human delay." },
      { label: "Human Hours Saved", value: "40+/mo", positive: true, icon: "clock", description: "Over 40 hours per month reclaimed from repetitive follow-up calls and scheduling." },
    ],
    href: "/work/ai-call-centre",
    subtitle: "One AI agent replaced an entire follow-up workflow — and started closing leads.",
    duration: "2 Week Build",
    accentColor: "amber",
    challengeHeading: "Good leads going cold because nobody followed up.",
    challengeDescription: [
      "This client was generating inbound leads through ads and referrals, but had no reliable system for following up. Some leads got a callback within a day, others waited three or four days, and many never heard back at all.",
      "The owner knew they were losing revenue, but couldn't afford to hire a full-time receptionist or call centre team. Every missed follow-up was a missed appointment — and the longer a lead waited, the less likely they were to convert.",
    ],
    challengeItems: [
      { icon: "phone-missed", title: "Inconsistent Follow-Up", description: "No system in place — some leads got a call in hours, others never received one at all." },
      { icon: "user-x", title: "No Dedicated Staff", description: "The business couldn't justify a full-time hire just for follow-up, so it kept falling through the cracks." },
      { icon: "clock", title: "Leads Going Cold", description: "Average first-contact time was 2–3 days. By then, most leads had already booked with a competitor." },
    ],
    strategyHeading: "An AI agent that never misses a lead.",
    strategyItems: [
      { icon: "bot", title: "AI Call Centre Agent", description: "Built a conversational AI agent that calls or texts every new lead within 60 seconds of submission — qualifying, answering questions, and scheduling appointments automatically.", color: "amber" },
      { icon: "workflow", title: "CRM Integration", description: "Connected the AI agent to the client's CRM so every interaction is logged, follow-ups are tracked, and no lead falls through the cracks.", color: "violet" },
      { icon: "repeat", title: "Multi-Touch Sequences", description: "Designed automated follow-up sequences — if the lead doesn't respond on the first attempt, the AI retries via text and call across a 7-day cadence.", color: "amber" },
    ],
    quote: { text: "Before this, half our leads disappeared. Now every single one gets a call within a minute. We're booking 10–12 new clients a month without lifting a finger.", author: "Business Owner" },
    takeaway: "Most businesses don't have a lead generation problem — they have a lead follow-up problem. An AI call agent can solve it for a fraction of the cost of a full-time hire, and it never takes a day off.",
  },
];

export const services: Service[] = [
  {
    id: "web-development",
    icon: "Code",
    title: "Website & Web App Development",
    description:
      "Custom Next.js websites and full-stack web applications — server-rendered, SEO-optimized, and built with React, TypeScript, and Tailwind CSS.",
    outcomes: [
      "Custom Next.js website or web app",
      "Auth, dashboards, and API integrations",
      "SEO foundation built into every page",
    ],
    tags: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
  },
  {
    id: "wordpress",
    icon: "Globe",
    title: "WordPress Development",
    description:
      "Professional WordPress websites with custom themes, optimized performance, and SEO-ready architecture — built for businesses that need reliability and speed.",
    outcomes: [
      "Custom WordPress theme development",
      "Performance & security optimization",
      "SEO and mobile-responsive design",
    ],
    tags: ["WordPress", "PHP", "Custom Themes", "SEO"],
  },
  {
    id: "shopify",
    icon: "ShoppingCart",
    title: "Shopify Store Development",
    description:
      "E-commerce stores built on Shopify with custom themes, optimized product pages, and conversion-focused design that drives online sales.",
    outcomes: [
      "Custom Shopify theme design",
      "Product catalog & checkout optimization",
      "E-commerce SEO & conversion setup",
    ],
    tags: ["Shopify", "Liquid", "E-Commerce", "SEO"],
  },
  {
    id: "seo-aeo-geo",
    icon: "Search",
    title: "SEO / AEO / GEO",
    description:
      "Technical SEO, AI search optimization (AEO), and geo-targeted search strategies (GEO) — built to rank on Google and get cited by AI engines.",
    outcomes: [
      "Technical SEO audits & fixes",
      "AI search optimization (AEO/GEO)",
      "Content strategy & structured data",
    ],
    tags: ["SEO", "AEO", "GEO", "Schema Markup"],
  },
  {
    id: "automation",
    icon: "Zap",
    title: "Marketing Automation",
    description:
      "n8n workflows, CRM integrations, AI follow-up systems, and live dashboards — automating the repetitive work so your team can focus on growth.",
    outcomes: [
      "Custom n8n workflow builds",
      "CRM & tool integrations",
      "AI-powered follow-up sequences",
    ],
    tags: ["n8n", "CRM", "AI Agents", "Dashboards"],
  },
];

export const stats: Stat[] = [
  { value: 14, suffix: "+", label: "Websites Shipped", sublabel: "Next.js, WordPress, and Shopify projects delivered" },
  { value: 5, suffix: "", label: "Next.js Web Apps", sublabel: "Full-stack applications with auth, dashboards, and APIs" },
  { value: 340, suffix: "%", label: "Organic Growth", sublabel: "from near-zero to top-10 rankings" },
  { value: 20, suffix: "+", label: "Hours Saved / Week", sublabel: "via n8n automation systems" },
];

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    quote:
      "He was highly responsive, punctual, and always available to support the team when needed. His reliability and proactive approach made him an invaluable part of our operations. We are confident that Shree will excel in all his future endeavors. It was a pleasure working with him!",
    name: "Sharon Bechor",
    role: "CEO",
    company: "Rock and Soul DJ Equipment and Records",
    avatarInitials: "SB",
    avatarColor: "#F59E0B",
    avatarImage: "/Client-review-image/sharon-bechor.jpeg",
    stars: 5,
    result: "Reliable, proactive, and punctual",
    industry: "ecommerce",
  },
  {
    id: "t2",
    quote:
      "Shree is super smart, optimistic, creative, resourceful and mature! He is a \u201Cquick-study\u201D and works with a sense of dedication and care that builds confidence. His vision and technical abilities will be an asset. Shree is a technical leader \u2026 skilled technician, sure \u2026 but he is more of a leader in our experience!",
    name: "Jeff Klubeck",
    role: "Owner",
    company: "Get A Klu, Inc.",
    avatarInitials: "JK",
    avatarColor: "#7C3AED",
    avatarImage: "/Client-review-image/jeff-klubeck.jpeg",
    stars: 5,
    result: "Technical leader and quick study",
    industry: "services",
  },
  {
    id: "t3",
    quote:
      "Shree is very professional in all areas. He followed through with projects and was very creative with design and use of our brand. I would highly recommend Shree.",
    name: "Susan Peters",
    role: "CEO",
    company: "PossAbilities Plus",
    avatarInitials: "SP",
    avatarColor: "#22D3EE",
    avatarImage: "/Client-review-image/susan-peters.jpeg",
    stars: 5,
    result: "Creative design and brand execution",
    industry: "services",
  },
  {
    id: "t4",
    quote:
      "Shree is very capable and receptive to feedback. He is easy to work with. To deliver the best results, it would be helpful to provide detailed instructions and ensure the work is carefully reviewed.",
    name: "Olivia Yan",
    role: "Owner",
    company: "Olivia\u2019s Tanghulu",
    avatarInitials: "OY",
    avatarColor: "#34D399",
    avatarImage: "/Client-review-image/olivia-yan.jpeg",
    stars: 4,
    result: "Capable and receptive to feedback",
    industry: "ecommerce",
  },
  {
    id: "t5",
    quote:
      "Shree is a dedicated individual and showed great capability during his tenure with us at Tacklers Consulting Group! It\u2019s been a pleasure to see you grow and push us out of our comfort zone as well. Will be following your journey closely.",
    name: "Tacklers Consulting",
    role: "Owner",
    company: "Tacklers Consulting Group",
    avatarInitials: "TC",
    avatarColor: "#A855F7",
    avatarImage: "/Client-review-image/tacklers-consulting.jpeg",
    stars: 5,
    result: "Dedicated and pushed boundaries",
    industry: "finance",
  },
];

export const articles: Article[] = [
  {
    id: "a1",
    category: "Web Development",
    title: "Why Next.js Is the Best Framework for SEO-First Websites",
    excerpt:
      "Server-side rendering, static generation, and built-in image optimization — here's why Next.js outperforms every other framework for SEO.",
    date: "March 2025",
    readTime: "8 min read",
    href: "/blogs/nextjs-best-framework-seo",
    gradient: "from-violet-900/40 to-purple-900/20",
  },
  {
    id: "a2",
    category: "Automation",
    title: "Why Most n8n Workflows Break in Production (And How to Fix Them)",
    excerpt:
      "Building a workflow that runs in dev is easy. Building one that runs reliably in production for 6 months is a different discipline.",
    date: "February 2025",
    readTime: "6 min read",
    href: "/blogs/n8n-workflows-production",
    gradient: "from-cyan-900/40 to-teal-900/20",
  },
  {
    id: "a3",
    category: "SEO",
    title: "AEO vs SEO: How AI Search Engines Change Everything for Your Website",
    excerpt:
      "Google isn't the only search engine anymore. AI engines like ChatGPT, Perplexity, and Gemini are changing how businesses get found online.",
    date: "January 2025",
    readTime: "7 min read",
    href: "/blogs/aeo-vs-seo-ai-search",
    gradient: "from-amber-900/40 to-orange-900/20",
  },
];
