import { NextRequest, NextResponse } from 'next/server';
import { setAppAuthCookie, verifyAppAuthToken } from '@/lib/app-session';

/**
 * Accepts a JWT token (generated by the OAuth callback popup) and sets it
 * as an httpOnly cookie in the caller's browsing context.
 *
 * This exists because modern browsers may block Set-Cookie from a popup
 * window that went through a third-party redirect chain (Google OAuth).
 * By having the *main* window call this endpoint, the cookie is set in
 * a first-party context and is always available.
 */
export async function POST(req: NextRequest) {
  try {
    const { token } = await req.json();
    if (!token) {
      return NextResponse.json({ error: 'Missing token' }, { status: 400 });
    }

    verifyAppAuthToken(token);

    const response = NextResponse.json({ success: true });
    setAppAuthCookie(response, token);

    return response;
  } catch (error) {
    console.error('Token login error:', error);
    return NextResponse.json({ error: 'Invalid token' }, { status: 401 });
  }
}
